/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getRuntimeHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["getRuntimeCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CapabilitiesData */
        CapabilitiesData: {
            runtimeId: components["schemas"]["Uuid"];
            generation: components["schemas"]["Generation"];
            /** Capabilities */
            capabilities: components["schemas"]["Capability"][];
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            requestId: components["schemas"]["Uuid"];
            data: components["schemas"]["CapabilitiesData"];
        };
        /** Capability */
        Capability: {
            id: components["schemas"]["CapabilityId"];
            /** Enabled */
            enabled: boolean;
            /**
             * Reasoncode
             * @enum {string}
             */
            reasonCode: "AVAILABLE" | "NOT_IMPLEMENTED";
        };
        /** @enum {string} */
        CapabilityId: "runtime" | "projects" | "credentials" | "story" | "visualAssets" | "storyboard" | "video" | "audio" | "timeline" | "checks" | "exports" | "costs";
        /** @enum {string} */
        ErrorCode: "AUTH_REQUIRED" | "AUTH_INVALID" | "HOST_REJECTED" | "ORIGIN_REJECTED" | "REQUEST_INVALID" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "BACKEND_NOT_READY" | "INTERNAL_ERROR";
        /** ErrorDetail */
        ErrorDetail: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /** Affectedids */
            affectedIds: components["schemas"]["Uuid"][];
            recoverableAction: components["schemas"]["RecoveryAction"];
        };
        /** ErrorResponse */
        ErrorResponse: {
            requestId: components["schemas"]["Uuid"];
            error: components["schemas"]["ErrorDetail"];
        };
        Generation: number;
        /** HealthData */
        HealthData: {
            /**
             * Status
             * @constant
             */
            status: "ready";
            runtimeId: components["schemas"]["Uuid"];
            generation: components["schemas"]["Generation"];
            apiVersion: components["schemas"]["ProtocolVersion"];
            controlVersion: components["schemas"]["ProtocolVersion"];
            backendVersion: components["schemas"]["Version"];
            uptimeMs: components["schemas"]["SafeMilliseconds"];
        };
        /** HealthResponse */
        HealthResponse: {
            requestId: components["schemas"]["Uuid"];
            data: components["schemas"]["HealthData"];
        };
        /** @constant */
        ProtocolVersion: 1;
        /** @enum {string} */
        RecoveryAction: "none" | "retry_connection" | "restart_backend" | "repair_installation";
        SafeMilliseconds: number;
        /** Format: uuid */
        Uuid: string;
        Version: string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRuntimeHealth: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-Id"?: components["schemas"]["Uuid"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRuntimeCapabilities: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-Id"?: components["schemas"]["Uuid"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    "X-Request-Id"?: components["schemas"]["Uuid"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
